CREATE TABLE USER_DETAILS 
(
  USERNAME VARCHAR2(20 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) NOT NULL 
, ROLE_ID NUMBER NOT NULL 
, CONSTRAINT USER_DETAILS_PK PRIMARY KEY 
  (
    USERNAME 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ROLE_DETAILS 
(
  ROLE_ID NUMBER NOT NULL 
, ROLE_NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT ROLE_DETAILS_PK PRIMARY KEY 
  (
    ROLE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE QUERY_DETAILS 
(
  QUERY_ID NUMBER NOT NULL 
, QUERY VARCHAR2(200 BYTE) 
, ANSWER VARCHAR2(200 BYTE) 
, QUERY_STATUS VARCHAR2(20 BYTE) NOT NULL 
, PRESENTOR_NAME VARCHAR2(20 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PERSONAL_INFO 
(
  FNAME VARCHAR2(20 BYTE) NOT NULL 
, LNAME VARCHAR2(20 BYTE) NOT NULL 
, PHONE_NO VARCHAR2(20 BYTE) NOT NULL 
, EMAIL_ID VARCHAR2(20 BYTE) NOT NULL 
, USERNAME VARCHAR2(20 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE EVENT_SCHEDULING 
(
  EVENT_ID NUMBER NOT NULL 
, EVENT_DETAILS VARCHAR2(200 BYTE) NOT NULL 
, DATE_OF_EVENT DATE NOT NULL 
, TIME_OF_EVENT DATE NOT NULL 
, LOCATION VARCHAR2(100 BYTE) 
, PRESENTOR_NAME VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ARTIFACT_DETAILS 
(
  ARTIFACT_ID NUMBER NOT NULL 
, ARTIFACT_TITLE VARCHAR2(100 BYTE) NOT NULL 
, KEYFIELD VARCHAR2(20 BYTE) NOT NULL 
, STATUS VARCHAR2(20 BYTE) 
, EDITOR_NAME VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE ARTIFACT_BACKUP 
(
  ARTIFACT_FILE CLOB 
, ARTIFACT_ID NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
LOB (ARTIFACT_FILE) STORE AS SYS_LOB0000013750C00001$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  STORAGE 
  ( 
    INITIAL 65536 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);

ALTER TABLE USER_DETAILS
ADD CONSTRAINT USER_DETAILS_ROLE_DETAILS_FK1 FOREIGN KEY
(
  ROLE_ID 
)
REFERENCES ROLE_DETAILS
(
  ROLE_ID 
)
ENABLE;

ALTER TABLE QUERY_DETAILS
ADD CONSTRAINT QUERY_DETAILS_USER_DETAIL_FK1 FOREIGN KEY
(
  PRESENTOR_NAME 
)
REFERENCES USER_DETAILS
(
  USERNAME 
)
ENABLE;

ALTER TABLE EVENT_SCHEDULING
ADD CONSTRAINT EVENT_SCHEDULING_USER_DET_FK1 FOREIGN KEY
(
  PRESENTOR_NAME 
)
REFERENCES USER_DETAILS
(
  USERNAME 
)
ENABLE;

ALTER TABLE ARTIFACT_DETAILS
ADD CONSTRAINT ARTIFACT_DETAILS_USER_DET_FK1 FOREIGN KEY
(
  EDITOR_NAME 
)
REFERENCES USER_DETAILS
(
  USERNAME 
)
ENABLE;
